config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/the_gossip_project")

  resources :the_gossip_project
  resources :users
  resources :city
  resources :sessions, only:[:new, :create, :destroy]

  get '/contact', to: 'the_gossip_project#contact'

  get '/team', to: 'the_gossip_project#team'
  
  get "up" => "rails/health#show", as: :rails_health_check

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    has_many :gossips, through: :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord

    validates :title, presence: true, length: { in: 3..14 }
    validates :content, presence: true
    
    belongs_to :user
    has_many :tags
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
    validates :password, presence: true, length: { minimum: 6 }
    
    belongs_to :city
    has_many :gossips
    has_secure_password
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    def show
        index = params[:id].to_i
        @element = User.all[index - 1]
        @city = @element.city
    end

    def index
    end

    def create
    end

    def update
    end

    def edit
    end

    def new
    end

    def destroy
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include SessionsHelper
    def new

    end

    def create
        @user = User.find_by(email: params[:email])
        
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:success] = "Bienvenue, tu es maintenant connecté à ta session"
        redirect_to the_gossip_project_index_path
      else
        flash.now[:alert] = "Email ou mot de passe invalide"
        render 'new'
      end  
    end

    def destroy
        session.delete(:user_id)
        redirect_to root_path
        flash[:success] = "Tu es bien déconnecté"
    end
end

app/controllers/the_gossip_project_controller.rb
class TheGossipProjectController < ApplicationController

  def team
  end

  def contact
  end

  def index
    @gossips = Gossip.all
  end

  def create
    @gossips = Gossip.new(title: params[:title],
                          content: params[:content])
    @gossips.user = User.find_by(id: session[:user_id])

      if @gossips.save
        flash[:success] = "Gossip saved successfully"
        redirect_to the_gossip_project_index_path
      else
        flash[:alert] = "No way il manque des choses"
        render 'new'
      end             
  end

  def edit
    # @gossip = Gossip.find(params[:id])
  end

  def show
    index = params[:id].to_i
    @element = Gossip.all[index - 1]

  end

  def update
    @model = Model.find(params[:id])
    if @model.update(params[:id])
      redirect_to @model
      flash[:success] = "Bien joué, tu as bien modifié le gossip !"
    else
      render :edit
    end
  end

# def update
#     gossip_params = params.require(:gossip).permit(:title, :content)
#     @gossip = Gossip.find_by(id: params[:id])
#     @gossip.update(gossip_params)

#   end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        index = params[:id].to_i
        @element = Gossip.all[index - 1]
        @user = @element.user
    end

    def index
    end

    def create
        @users = User.new(email: params[:email],
                        first_name: params[:first_name],
                        last_name: params[:last_name],
                        age: params[:age],
                        description: params[:description],
                        password: params[:password],
                        password_confirmation: params[:password_confirmation],
                        city_id: 127)
    
      if @users.save
        @users.authenticate(params[:password])
        flash[:success] = "Bien joué, ton compte a bien été créé!"
        redirect_to the_gossip_project_index_path
      else
        flash[:alert] = "C'est mort pour toi, rééssaye"
        render 'new'
      end  
    end

    def update
    end

    def edit
    end

    def new

    end

    def destroy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/the_gossip_project_helper.rb
module TheGossipProjectHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/city/show.html.erb
<head>
</head>


  <h1>TheGossipProject</h1>

  <div class="button">
    <a href="http://localhost:3000/the_gossip_project/new">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Créer un Gossip! +</button>
    </a>
  </div> 
  
  <p> --> Nom de la ville : <%= @element.city.name %></p>

  <% users_in_same_city = User.where(city_id: @element.city_id) %>
  <% users_in_same_city.each do |user|%>
    <%= user.gossips.each do |gossip| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
      </div>
    </div>
    <% end %>
  <% end %>

<div class="link">
  <a class="return-link" href="http://localhost:3000/the_gossip_project">Revenir à la page d'accueil</a>
</div>
  </br>
<div class="link2">
  <%= link_to "En savoir plus sur l'auteur", user_path, class:"return-link2" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>TheGossipProject</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
  </head>

  <body data_turbo="false">

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "TGP", the_gossip_project_index_path, :class=>"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", the_gossip_project_index_path, :class=>"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, :class=>"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, :class=>"nav-link" %>
          </li>
          <div class="navbar-nav ml-auto">
            <% if current_user %>
              <div class="dropdown"
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mon compte
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Mon profil</a>
                    <%= button_to "Se déconnecter", session_path(session.id), :class=>"dropdown_item", method: :delete %>
                  </div>
                </li> 
              </div>      
            <% else %>
              <div class="dropdown"
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Connexion/Inscription
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "S'inscrire", new_user_path, :class=>"dropdown-item" %>
                    <%= link_to "Se connecter", new_session_path, :class=>"dropdown-item" %>
                  </div>
                </li>
              </div>    
            <% end %>
          </div> 
        </ul>
      </div>
    </nav>
  </header> 
 

    <% if flash[:success].present? %>
        <div class="alert alert-success custom_alert" role="alert">
          <%= flash[:success] %>
        </div>
      <% elsif flash[:alert].present? %>
        <div class="alert alert-danger custom_alert" role="alert">
          <%= flash[:alert] %>
        </div>
    <% end %>

  <%= yield %>

  </body>

</html>

app/views/the_gossip_project/contact.html.erb
<head>
</head>

<h1>TheGossipProject</h1>
<p>Voici nos contacts!!!</p>

app/views/the_gossip_project/edit.html.erb
<head>

</head>


  <h1>TheGossipProject</h1>

<div class="button">
  <a href="http://localhost:3000/the_gossip_project/new">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Créer un Gossip! +</button>
  </a>
</div> 

<h2>Tu veux modifier ce gossip ?</h2>
<div class="formulaire">
  <%= form_for @gossip, url: the_gossip_project_path(@gossip), method: :patch do |f| %>
    <%= f.label_tag :title, 'Titre' %>
    <%= f.text_field_tag :titre %>
    <br /> <br />

    <%= f.label_tag :content, 'Contenu' %>
    <%= f.text_field_tag :content %>
    <br /> <br />

    <%= f.submit_tag "Modifier" %>
  <% end %>
</div>  

<div class="link">
  <a class="return-link" href="http://localhost:3000/the_gossip_project">Revenir à la page d'accueil</a>
</div>
  </br>
<div class="link2">
  <%= link_to "En savoir plus sur l'auteur", user_path, class:"return-link2" %>
</div>

app/views/the_gossip_project/index.html.erb
<head>

</head>


<h1>TheGossipProject</h1>
<h2>Bienvenue à toi cher gossipeur !</h2>

<% if current_user %>
  <div class="button">
    <%= link_to "Créer un Gossip! +", new_the_gossip_project_path, :class=>"btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% else %>
  <div class="button">
    <%= link_to "Créer un Gossip! +", new_the_gossip_project_path, :class=>"btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>


<p>Voici tous les gossips qui ont été écrit :</p>

<div class="container">
  <div class="row">
    <% @gossips.each_with_index do |i, index|%>
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body ">
              <h5 class="card-title"><%= "#{i.user.first_name}"%>
              <h6 class="card-subtitle mb-2 text-muted"><%="#{i.title}" %></h6>
              <%= link_to "Voir le gossip", the_gossip_project_path(id: index +1), class:"mon-style-css" %>
              <%= link_to "Modifier le gossip", edit_the_gossip_project_path(id: index +1), class:"mon-style-css" %>
          </div>
        </div>
      </div> 
    <% end %> <!-- pour chaque itération, on appelle le first_name du user correspondant au titre de son gossip -->
  </div>  
</div>

app/views/the_gossip_project/new.html.erb
<head>

</head>

<body>
<h1>TheGossipProject</h1>
<h2>Créer ton gossip en direct !</h2>

<div class="formulaire">
<%= form_for Gossip.new, url: the_gossip_project_index_path do %>
  <%= label_tag :title, 'Titre' %>
    <%= text_field_tag :title %>
    <br /> <br />

    <%= label_tag :content, 'Contenu' %>
    <%= text_area_tag :content %>
    <br /> <br />

    <%= submit_tag "Créer Gossip" %>

<% end %>


</div>

</body>

app/views/the_gossip_project/show.html.erb
<head>

</head>


  <h1>TheGossipProject</h1>

<div class="button">
  <%= link_to "Créer un Gossip! +", new_the_gossip_project_path, :class=>"btn btn-outline-success my-2 my-sm-0" %>
</div> 

  <p> --> Auteur : <p> 
  <p> <%= @element.user.first_name %> </p>
  <p> --> Titre : <p>
  <p> <%= @element.title %> </p>
  <p> --> Contenu :</p>
  <p> <%= @element.content %> </p>
  <p> --> Ville de l'auteur :</p>
  <p> <%= @element.user.city.name %> </p>
  <%= link_to "En savoir plus sur la ville", city_path %>

<div class="link">
  <%= link_to "Revenir à la page d'accueil", the_gossip_project_index_path, :class=>"return-link" %>
</div>
  </br>
<div class="link2">
  <%= link_to "En savoir plus sur l'auteur", user_path, class:"return-link2" %>
</div>

app/views/the_gossip_project/team.html.erb
<head>
</head>

<h1>TheGossipProject</h1>
<p>Voici notre équipe !!!!</p>

app/views/the_gossip_project/welcome.html.erb
<head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="http://localhost:3000/the_gossip_project/home">TGP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/the_gossip_project/home">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/the_gossip_project/team">Team</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="http://localhost:3000/the_gossip_project/contact">Contact</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</head>

<h1>TheGossipProject</h1>
<p>Bienvenue <%= @first_name %>, tu retrouveras sur ce site un tas de potin concernant les membres de la formation The Hacking Project! </p>

app/views/users/index.html.erb
<head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="http://localhost:3000/the_gossip_project/home">TGP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/the_gossip_project">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/team">Team</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="http://localhost:3000/contact">Contact</a>
      </li>
    </ul>
    <a href="http://localhost:3000/the_gossip_project/new">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Créer un Gossip!</button>
    </a>
  </div>
</nav>
</head>


  <h1>C'est le indexxxxx</h1>
  <p> --> Auteur : <p> 
  <p> <%= @element.user.first_name %> </p>
  <p> --> Titre : <p>
  <p> <%= @element.title %> </p>
  <p> --> Contenu :</p>
  <p> <%= @element.content %> </p>
  <p> --> Ville de l'auteur :</p>
  <p> <%= @element.user.city.name %> </p>

  <a class="return-link" href="http://localhost:3000/the_gossip_project">Revenir à la page d'accueil</a>
  </br>
  <%= link_to "Retourner au gossip", the_gossip_project_path(id: index +1), class:"return-link2" %>

app/views/users/new.html.erb
<head>

</head>

<body>
<h1>TheGossipProject</h1>

<h2>Si tu n'as pas encore de compte, créer ton profil utilisateur dès maintenant !</h2>

<div class="formulaire">
<%= form_for User.new, url: users_path do %>
  <%= label_tag :first_name, 'Prénom' %>
  <br /> <br />
    <%= text_field_tag :first_name %>
    <br /> <br />
    
  <%= label_tag :last_name, 'Nom de famille' %>
  <br /> <br />
    <%= text_field_tag :last_name %>
    <br /> <br />

  <%= label_tag :age, 'Age' %>
  <br /> <br />
    <%= text_field_tag :age %>
    <br /> <br />

  <%= label_tag :description, 'Description' %>
  <br /> <br />
    <%= text_area_tag :description %>
    <br /> <br />

  <%= label_tag :email, 'Email' %>
  <br /> <br />
    <%= text_field_tag :email %>
    <br /> <br />

    <%= label_tag :password, 'Mot de passe' %>
    <br /> <br />
    <%= text_field_tag :password %>
    <br /> <br />

    <%= label_tag :password_confirmation, 'Confirmation' %>
    <br /> <br />
    <%= text_field_tag :password_confirmation %>
    <br /> <br />

    <%= submit_tag "S'inscrire" %>

<% end %>

  <%= link_to "Déjà un compte ? Se connecter", new_session_path, :class=>"nav-link" %>

</div>



</body>

app/views/users/show.html.erb
<head>

</head>


  <h1>TheGossipProject</h1>

<div class="button">
  <%= link_to "Créer un Gossip! +", new_the_gossip_project_path, :class=>"btn btn-outline-success my-2 my-sm-0" %>
</div> 

  <p> --> Auteur : <p> 
  <p> <%= @user.first_name %> <%= @user.last_name %> </p>
  <p> --> Description : <p>
  <p> <%= @user.description %> </p>
  <p> --> Email :</p>
  <p> <%= @user.email %> </p>
  <p> --> Age :</p>
  <p> <%= @user.age %> </p>
  <p> --> Ville :</p>
  <p> <%= @user.city.name %> </p>

<div class="link">
  <%= link_to "Revenir à la page d'accueil", the_gossip_project_index_path, :class=>"return-link" %>
</div>
  </br>
<div class="link2">
  <%= link_to "Retourner au gossip", the_gossip_project_path, class:"return-link2" %>
</div>